/**
 * Jenkinsfile for Playwright Test Automation
 * This pipeline checks out the code, installs dependencies, runs tests, and generates reports.
 */
pipeline {
    agent any

    tools {
        nodejs 'NodeJS'
    }

    environment {
        TEST_ENV = 'STAGE'
        CI = 'true'
    }

    stages {
        stage('Clean Reports') {
            steps {
                bat 'if exist allure-results rmdir /s /q allure-results'
                bat 'if exist allure-report rmdir /s /q allure-report'
                bat 'if exist playwright-report rmdir /s /q playwright-report'
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm install'
            }
        }

        stage('Install Browsers') {
            steps {
                bat 'npx playwright install'
            }
        }

        stage('Run Regression') {
            steps {
                bat 'npx playwright test'
            }
        }
    }

    post {
        always {
            allure([
            includeProperties: false,
            jdk: '',
            results: [[path: 'allure-results']]
        ])

            publishHTML(target: [
            allowMissing: true,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportDir: 'playwright-report',
            reportFiles: 'index.html',
            reportName: 'Playwright HTML Report'
        ])

            archiveArtifacts artifacts: 'playwright-report/**/*'
        }

        success {
            emailext(
            subject: "SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",

            body: """
            <h2>Playwright Execution Successful</h2>

            <p><b>Job:</b> ${env.JOB_NAME}</p>

            <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>

            <p><b>Status:</b> SUCCESS</p>

            <hr>

            <p>
            <a href="${env.BUILD_URL}allure">
            Open Allure Report
            </a>
            </p>

            <p>
            <a href="${env.BUILD_URL}Playwright_20HTML_20Report/">
            Open Playwright HTML Report
            </a>
            </p>

            <p>
            <a href="${env.BUILD_URL}console">
            Open Console Logs
            </a>
            </p>
            """,

            mimeType: 'text/html',

            to: 'ssongade0@gmail.com'
        )
        }

        failure {
            emailext(
            subject: "FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER}",

            body: """
            <h2>Playwright Execution Failed</h2>

            <p><b>Job:</b> ${env.JOB_NAME}</p>

            <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>

            <p><b>Status:</b> FAILED</p>

            <hr>

            <p>
            <a href="${env.BUILD_URL}allure">
            Open Allure Report
            </a>
            </p>

            <p>
            <a href="${env.BUILD_URL}Playwright_20HTML_20Report/">
            Open Playwright HTML Report
            </a>
            </p>

            <p>
            <a href="${env.BUILD_URL}console">
            Open Console Logs
            </a>
            </p>
            """,

            mimeType: 'text/html',

            to: 'ssongade0@gmail.com'
        )
        }
    }
}
